apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sy6lwbrrs-nodejs
  janus-idp.io/tekton: sy6lwbrrs-nodejs
  backstage.io/kubernetes-id: sy6lwbrrs-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sy6lwbrrs-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
